function [] = figCorela( abs_path )

global h_proc_1st;
global roi_pos_1st;
global pix_spac_1st;
global slope_1st;
global intercept_1st;
 
[read_res, low, high,...
    slope, intercept] = applyWinParams(abs_path);

fig1 = figure;
fig1.Visible = 'off';
fig1.Name = 'Fig 1st';
fig1.NumberTitle  = 'off';
target_fig = fig1;
tmp_show = imshow(read_res, [low, high]);
set(fig1, 'unit', 'normalized', 'position', [0,0,1,1]);

% ROI freehand 
pause on;

start_draw = uicontrol('style', 'pushbutton',...
                        'parent', fig1,...
                        'string', 'Draw ROI',...
                        'Position', [50, 500, 200, 90],...
                        'callback', 'h_proc_1st = imfreehand; roi_pos_1st = getPosition(h_proc_1st);')
show_SubPlot = uicontrol('style', 'pushbutton',...
                    'parent', fig1,...
                    'string', 'create SubPlot',...
                    'Position', [50, 400, 200, 90],...
                    'callback', '[x_data, y_data] = showSubPlot(h_proc_1st);');                    
start_calc = uicontrol('style', 'pushbutton',...
                        'parent', fig1,...
                        'string', 'Calculate HU values',...
                        'Position', [50, 300, 200, 90],...
                        'callback', 'CalcHu(h_proc_1st, read_res_1st, slope_1st, intercept_1st, pix_spac_1st);');
                    
create_reuse = uicontrol('style', 'pushbutton',...
                        'parent', fig1,...
                        'string', 'reuse the position',...
                        'Position', [50, 200, 200, 90],...
                        'callback', 'reUse(roi_pos_1st);');

uicontrol(start_draw);
hText=impixelinfoval(gcf, tmp_show);
set(hText,'FontWeight', 'bold')
set(hText,'FontSize',10)

end

